
spring:
  cloud:
    stream:
      function:
        definition: notificationEventsProcessor
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        bindings:
          notificationEventsProcessor-in-0:
            consumer:
              ackMode: BATCH
              enableDlq: true
              dlqName: notification-events-dlq
      bindings:
        notificationEventsProcessor-in-0:
          destination: notification-events
          group: notification-server
        notificationEventsProcessor-out-0:
          destination: notification-event-acks
        testNotificationProducer-out-0:
          destination: notification-events

notification-cache:
  host: localhost:6379
  standalone: true
  ttl: 86400
  maxIdleTime: 86400
  ssl: false
